Table:
I00: dd StopIf
I01: dd NoInstruction
I02: dd NoInstruction
I03: dd NoInstruction
I04: dd NoInstruction
I05: dd NoInstruction
I06: dd NoInstruction
I07: dd NoInstruction
I08: dd NoInstruction
I09: dd NoInstruction
I0A: dd NoInstruction
I0B: dd NoInstruction
I0C: dd NoInstruction
I0D: dd NoInstruction
I0E: dd NoInstruction
I0F: dd NoInstruction

I10: dd ConditionZ8
I11: dd ConditionE8
I12: dd ConditionG8
I13: dd ConditionL8
I14: dd ConditionNZ8
I15: dd ConditionNE8
I16: dd ConditionNG8
I17: dd ConditionNL8
I18: dd ConditionZ16
I19: dd ConditionE16
I1A: dd ConditionG16
I1B: dd ConditionL16
I1C: dd ConditionNZ16
I1D: dd ConditionNE16
I1E: dd ConditionNG16
I1F: dd ConditionNL16

I20: dd AddValueTo8
I21: dd Add8With8
I22: dd AddValueTo16
I23: dd Add16With16
I24: dd NoInstruction
I25: dd NoInstruction
I26: dd NoInstruction
I27: dd NoInstruction
I28: dd NoInstruction
I29: dd NoInstruction
I2A: dd NoInstruction
I2B: dd NoInstruction
I2C: dd NoInstruction
I2D: dd NoInstruction
I2E: dd NoInstruction
I2F: dd NoInstruction

I30: dd SubValueTo8
I31: dd Sub8With8
I32: dd SubValueTo16
I33: dd Sub16With16
I34: dd NoInstruction
I35: dd NoInstruction
I36: dd NoInstruction
I37: dd NoInstruction
I38: dd NoInstruction
I39: dd NoInstruction
I3A: dd NoInstruction
I3B: dd NoInstruction
I3C: dd NoInstruction
I3D: dd NoInstruction
I3E: dd NoInstruction
I3F: dd NoInstruction

I40: dd NoInstruction
I41: dd NoInstruction
I42: dd NoInstruction
I43: dd NoInstruction
I44: dd NoInstruction
I45: dd NoInstruction
I46: dd NoInstruction
I47: dd NoInstruction
I48: dd NoInstruction
I49: dd NoInstruction
I4A: dd NoInstruction
I4B: dd NoInstruction
I4C: dd NoInstruction
I4D: dd NoInstruction
I4E: dd NoInstruction
I4F: dd NoInstruction

I50: dd NoInstruction
I51: dd NoInstruction
I52: dd NoInstruction
I53: dd NoInstruction
I54: dd NoInstruction
I55: dd NoInstruction
I56: dd NoInstruction
I57: dd NoInstruction
I58: dd NoInstruction
I59: dd NoInstruction
I5A: dd NoInstruction
I5B: dd NoInstruction
I5C: dd NoInstruction
I5D: dd NoInstruction
I5E: dd NoInstruction
I5F: dd NoInstruction

I60: dd NoInstruction
I61: dd NoInstruction
I62: dd NoInstruction
I63: dd NoInstruction
I64: dd NoInstruction
I65: dd NoInstruction
I66: dd NoInstruction
I67: dd NoInstruction
I68: dd NoInstruction
I69: dd NoInstruction
I6A: dd NoInstruction
I6B: dd NoInstruction
I6C: dd NoInstruction
I6D: dd NoInstruction
I6E: dd NoInstruction
I6F: dd NoInstruction

I70: dd NoInstruction
I71: dd NoInstruction
I72: dd NoInstruction
I73: dd NoInstruction
I74: dd NoInstruction
I75: dd NoInstruction
I76: dd NoInstruction
I77: dd NoInstruction
I78: dd NoInstruction
I79: dd NoInstruction
I7A: dd NoInstruction
I7B: dd NoInstruction
I7C: dd NoInstruction
I7D: dd NoInstruction
I7E: dd NoInstruction
I7F: dd NoInstruction

I80: dd MovValueToByte
I81: dd Mov8To8
I82: dd MovValueToWord
I83: dd Mov16To16
I84: dd MovRegToMem8
I85: dd MovMem8ToReg
I86: dd MovRegToMem16
I87: dd MovMem16ToReg
I88: dd LoadSegment
I89: dd LoadFromSegment
I8A: dd NoInstruction
I8B: dd NoInstruction
I8C: dd NoInstruction
I8D: dd NoInstruction
I8E: dd NoInstruction
I8F: dd NoInstruction

I90: dd NoInstruction
I91: dd NoInstruction
I92: dd NoInstruction
I93: dd NoInstruction
I94: dd NoInstruction
I95: dd NoInstruction
I96: dd NoInstruction
I97: dd NoInstruction
I98: dd NoInstruction
I99: dd NoInstruction
I9A: dd NoInstruction
I9B: dd NoInstruction
I9C: dd NoInstruction
I9D: dd NoInstruction
I9E: dd NoInstruction
I9F: dd NoInstruction

IA0: dd NoInstruction
IA1: dd NoInstruction
IA2: dd NoInstruction
IA3: dd NoInstruction
IA4: dd NoInstruction
IA5: dd NoInstruction
IA6: dd NoInstruction
IA7: dd NoInstruction
IA8: dd NoInstruction
IA9: dd NoInstruction
IAA: dd NoInstruction
IAB: dd NoInstruction
IAC: dd NoInstruction
IAD: dd NoInstruction
IAE: dd NoInstruction
IAF: dd NoInstruction

IB0: dd NoInstruction
IB1: dd NoInstruction
IB2: dd NoInstruction
IB3: dd NoInstruction
IB4: dd NoInstruction
IB5: dd NoInstruction
IB6: dd NoInstruction
IB7: dd NoInstruction
IB8: dd NoInstruction
IB9: dd NoInstruction
IBA: dd NoInstruction
IBB: dd NoInstruction
IBC: dd NoInstruction
IBD: dd NoInstruction
IBE: dd NoInstruction
IBF: dd NoInstruction

IC0: dd NoInstruction
IC1: dd NoInstruction
IC2: dd NoInstruction
IC3: dd NoInstruction
IC4: dd NoInstruction
IC5: dd NoInstruction
IC6: dd NoInstruction
IC7: dd NoInstruction
IC8: dd NoInstruction
IC9: dd NoInstruction
ICA: dd NoInstruction
ICB: dd NoInstruction
ICC: dd NoInstruction
ICD: dd NoInstruction
ICE: dd NoInstruction
ICF: dd NoInstruction

ID0: dd NoInstruction
ID1: dd NoInstruction
ID2: dd NoInstruction
ID3: dd NoInstruction
ID4: dd NoInstruction
ID5: dd NoInstruction
ID6: dd NoInstruction
ID7: dd NoInstruction
ID8: dd NoInstruction
ID9: dd NoInstruction
IDA: dd NoInstruction
IDB: dd NoInstruction
IDC: dd NoInstruction
IDD: dd NoInstruction
IDE: dd NoInstruction
IDF: dd NoInstruction

IE0: dd NoInstruction
IE1: dd NoInstruction
IE2: dd NoInstruction
IE3: dd NoInstruction
IE4: dd NoInstruction
IE5: dd NoInstruction
IE6: dd NoInstruction
IE7: dd NoInstruction
IE8: dd NoInstruction
IE9: dd NoInstruction
IEA: dd NoInstruction
IEB: dd NoInstruction
IEC: dd NoInstruction
IED: dd NoInstruction
IEE: dd NoInstruction
IEF: dd NoInstruction

IF0: dd NoInstruction
IF1: dd NoInstruction
IF2: dd NoInstruction
IF3: dd NoInstruction
IF4: dd NoInstruction
IF5: dd NoInstruction
IF6: dd NoInstruction
IF7: dd NoInstruction
IF8: dd NoInstruction
IF9: dd NoInstruction
IFA: dd NoInstruction
IFB: dd NoInstruction
IFC: dd NoInstruction
IFD: dd NoInstruction
IFE: dd NoInstruction
IFF: dd STOP